### ISSUE TITLE
Upgrade rest-assured version to 3.1.0

### ISSUE THREAD

**Issue by lucap84** [HotelsDotCom/heat#23]
HEAT is using a old version of REST Assured (2.9.0) that causes some issues, like a useless WARNING message regarding content-type: https://github.com/rest-assured/rest-assured/issues/715

We would like to move on version 3.1.0

```
<!-- https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>3.1.0</version>
    <scope>test</scope>
</dependency>

```

**Comment by AnnaritaX** [comment]
released in version 3.0.0
