### ISSUE TITLE
Misaligned rest-assured dependency versions in heat modules

### ISSUE THREAD

**Issue by lucap84** [HotelsDotCom/heat#29]
The  **internal-module** of HEAT has the dependency
https://github.com/HotelsDotCom/heat/blob/5fe7df520f02025c0ac01583d3855eec12993d74/heat-internal-modules/pom.xml#L32

Instead of the newer version used in main pom.xml
https://github.com/HotelsDotCom/heat/blob/5fe7df520f02025c0ac01583d3855eec12993d74/pom.xml#L63

This could cause issues like
`Wrong 1st argument type. Found: 'io.restassured.response.Response', required: 'com.jayway.restassured.response.Response'` using WiremockUtils methods.

**Comment by AnnaritaX** [comment]
Fixed
