### ISSUE TITLE
Support for OPTIONS HTTP Request

### ISSUE THREAD

**Issue by fsferrara** [HotelsDotCom/heat#34]
Shall we add the capability to perform OPTION HTTP Request to the service under test?
This feature can be useful to test if the service under test can properly respond to a preflight requests.

In the context of a CORS request, a preflight request may be used by the browser to perform a check against the service before actually triggering the CORS call.

This is an example of preflight request 
```
curl 'https://example.com/context/graphql' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: chrome-search://local-ntp' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' -H 'Access-Control-Request-Headers: access-control-allow-origin,content-type,x-client-id' --compressed
```

**Comment by fsferrara** [comment]
Just raised the PR #35 for this issue.

**Comment by AnnaritaX** [comment]
Resolved
